### PR TITLE
make postinstall an option instead of a positional parameter

### PR DESCRIPTION
**Pull request by doniks**
also remove spinner

### CODE REVIEW

**Comment by jbruechert** [comment]
Thanks for your PR! Like this, the script probably outputs lots if debug messages from the subcommands. Would it be possible to add a -v / --verbose option to control if output is redirected into /dev/null? I think this amount of output is more confusing than useful for most users. If anyone else reads this, what do you think? Otherwise thank you for the much better command line parameter parser, that's something I postponed a lot of times :)

**Comment by doniks** [comment]
added a -v option. It's a bit hackish, but it seems to work ok. 

I would want to still test it a bit more - had some trouble yesterday with a pm install - it seemed to not take the root password. I actually suspect the problem is in front of the screen, but I want to be sure. 

However, I'll update the PR already for your review.

**Comment by jbruechert** [comment]
Thank you for implementing that :). After a little bit of testing I will merge the PR.

**Comment by doniks** [comment]
1. about this
> had some trouble yesterday with a pm install - [...] I actually suspect the problem is in front of the screen

Indeed, was just my fault. pm is installed correctly. (it doesn't bring up UI but that's an unrelated problem)

2. I realise that my commit msg is wrong. Please change it to something like:

make postinstall an option instead of a positional parameter

3. maybe `function quiet` should actually go in another file?! let me know if you want it moved

**Pull request merged**
