### PR TITLE
Pw3

### PR DESCRIPTION
**Pull request by doniks**
two commits to set ssh key and simplify password setting

### CODE REVIEW

**Comment by jbruechert** [comment]
Codacy still needs some time ... lets wait for it.

**Comment by doniks** [comment]
mhm ... codacy doesn't like `sudo tee -a outfile < infile`, but it didn't like `cat infile | sudo tee -a outfile` either

**Comment by jbruechert** [comment]
Yes, that looks like a bug in codacy. Let me check tomorrow.

**Comment by jbruechert** [comment]
Merged, although GitHub doesn't detect it. (Can't merge on GitHub as the main repo is on GitLab)

**Pull request closed without merging**
