### PR TITLE
Ubuntu touch support

### PR DESCRIPTION
**Pull request by jbruechert**

### CODE REVIEW

**Comment by doniks** [comment]
I tried on deb, but it goes into a bootloop. Trying to mount the rootfs in TWRP seems to indicate that the fs is not ok 

https://paste.ubuntu.com/26349815/

**Comment by jbruechert** [comment]
Could you use images produced by this script before this change? This script is using ext4 instead of ext2, maybe that's a problem

**Comment by jbruechert** [comment]
btw, to enable the ubuntu touch hook, run `halium-install rootfs.tar system.img ut`

**Comment by jbruechert** [comment]
I'm going to merge this for now, as some other changes depend on it.

**Pull request merged**
